In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x1 = tf.cast(tf.Variable(np.arange(48).reshape(3,4,4)), tf.int32)
x2 = tf.cast(tf.Variable(np.arange(48).reshape(3,4,4)), tf.int32)
x3 = tf.cast(tf.Variable(np.arange(48).reshape(3,4,4)), tf.int32)
x4 = tf.cast(tf.Variable(np.arange(48).reshape(3,4,4)), tf.int32)

In [3]:
xx1 = tf.pad(x1, paddings=[[0, 0], [0, 4], [0, 4]], mode="CONSTANT")
xx2 = tf.pad(x2, paddings=[[0, 0], [4, 0], [0, 4]], mode="CONSTANT")
xx3 = tf.pad(x3, paddings=[[0, 0], [0, 4], [4, 0]], mode="CONSTANT")
xx4 = tf.pad(x4, paddings=[[0, 0], [4, 0], [4, 0]], mode="CONSTANT")

In [4]:
y1 = tf.add(xx1, xx2)
y2 = tf.add(y1, xx3)
y3 = tf.add(y2, xx4)

In [5]:
sess = tf.Session()

In [6]:
sess.run(tf.global_variables_initializer())

In [7]:
sess.run(x1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]], dtype=int32)

In [8]:
sess.run(xx1)

array([[[ 0,  1,  2,  3,  0,  0,  0,  0],
        [ 4,  5,  6,  7,  0,  0,  0,  0],
        [ 8,  9, 10, 11,  0,  0,  0,  0],
        [12, 13, 14, 15,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]],

       [[16, 17, 18, 19,  0,  0,  0,  0],
        [20, 21, 22, 23,  0,  0,  0,  0],
        [24, 25, 26, 27,  0,  0,  0,  0],
        [28, 29, 30, 31,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]],

       [[32, 33, 34, 35,  0,  0,  0,  0],
        [36, 37, 38, 39,  0,  0,  0,  0],
        [40, 41, 42, 43,  0,  0,  0,  0],
        [44, 45, 46, 47,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  

In [9]:
sess.run(xx2)

array([[[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  0,  0,  0,  0],
        [ 4,  5,  6,  7,  0,  0,  0,  0],
        [ 8,  9, 10, 11,  0,  0,  0,  0],
        [12, 13, 14, 15,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [16, 17, 18, 19,  0,  0,  0,  0],
        [20, 21, 22, 23,  0,  0,  0,  0],
        [24, 25, 26, 27,  0,  0,  0,  0],
        [28, 29, 30, 31,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [32, 33, 34, 35,  0,  0,  0,  0],
        [36, 37, 38, 39,  0,  0,  0,  0],
        [40, 41, 42, 43,  0,  0,  0,  0],
        [44, 45, 46, 47,  0,  

In [10]:
sess.run(xx3)

array([[[ 0,  0,  0,  0,  0,  1,  2,  3],
        [ 0,  0,  0,  0,  4,  5,  6,  7],
        [ 0,  0,  0,  0,  8,  9, 10, 11],
        [ 0,  0,  0,  0, 12, 13, 14, 15],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0, 16, 17, 18, 19],
        [ 0,  0,  0,  0, 20, 21, 22, 23],
        [ 0,  0,  0,  0, 24, 25, 26, 27],
        [ 0,  0,  0,  0, 28, 29, 30, 31],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0, 32, 33, 34, 35],
        [ 0,  0,  0,  0, 36, 37, 38, 39],
        [ 0,  0,  0,  0, 40, 41, 42, 43],
        [ 0,  0,  0,  0, 44, 45, 46, 47],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  

In [11]:
sess.run(xx4)

array([[[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  1,  2,  3],
        [ 0,  0,  0,  0,  4,  5,  6,  7],
        [ 0,  0,  0,  0,  8,  9, 10, 11],
        [ 0,  0,  0,  0, 12, 13, 14, 15]],

       [[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, 16, 17, 18, 19],
        [ 0,  0,  0,  0, 20, 21, 22, 23],
        [ 0,  0,  0,  0, 24, 25, 26, 27],
        [ 0,  0,  0,  0, 28, 29, 30, 31]],

       [[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, 32, 33, 34, 35],
        [ 0,  0,  0,  0, 36, 37, 38, 39],
        [ 0,  0,  0,  0, 40, 41, 42, 43],
        [ 0,  0,  0,  0, 44, 4

In [12]:
sess.run(y1)

array([[[ 0,  1,  2,  3,  0,  0,  0,  0],
        [ 4,  5,  6,  7,  0,  0,  0,  0],
        [ 8,  9, 10, 11,  0,  0,  0,  0],
        [12, 13, 14, 15,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  0,  0,  0,  0],
        [ 4,  5,  6,  7,  0,  0,  0,  0],
        [ 8,  9, 10, 11,  0,  0,  0,  0],
        [12, 13, 14, 15,  0,  0,  0,  0]],

       [[16, 17, 18, 19,  0,  0,  0,  0],
        [20, 21, 22, 23,  0,  0,  0,  0],
        [24, 25, 26, 27,  0,  0,  0,  0],
        [28, 29, 30, 31,  0,  0,  0,  0],
        [16, 17, 18, 19,  0,  0,  0,  0],
        [20, 21, 22, 23,  0,  0,  0,  0],
        [24, 25, 26, 27,  0,  0,  0,  0],
        [28, 29, 30, 31,  0,  0,  0,  0]],

       [[32, 33, 34, 35,  0,  0,  0,  0],
        [36, 37, 38, 39,  0,  0,  0,  0],
        [40, 41, 42, 43,  0,  0,  0,  0],
        [44, 45, 46, 47,  0,  0,  0,  0],
        [32, 33, 34, 35,  0,  0,  0,  0],
        [36, 37, 38, 39,  0,  0,  0,  0],
        [40, 41, 42, 43,  0,  0,  0,  0],
        [44, 45, 46, 47,  0,  

In [13]:
sess.run(y2)

array([[[ 0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11],
        [12, 13, 14, 15, 12, 13, 14, 15],
        [ 0,  1,  2,  3,  0,  0,  0,  0],
        [ 4,  5,  6,  7,  0,  0,  0,  0],
        [ 8,  9, 10, 11,  0,  0,  0,  0],
        [12, 13, 14, 15,  0,  0,  0,  0]],

       [[16, 17, 18, 19, 16, 17, 18, 19],
        [20, 21, 22, 23, 20, 21, 22, 23],
        [24, 25, 26, 27, 24, 25, 26, 27],
        [28, 29, 30, 31, 28, 29, 30, 31],
        [16, 17, 18, 19,  0,  0,  0,  0],
        [20, 21, 22, 23,  0,  0,  0,  0],
        [24, 25, 26, 27,  0,  0,  0,  0],
        [28, 29, 30, 31,  0,  0,  0,  0]],

       [[32, 33, 34, 35, 32, 33, 34, 35],
        [36, 37, 38, 39, 36, 37, 38, 39],
        [40, 41, 42, 43, 40, 41, 42, 43],
        [44, 45, 46, 47, 44, 45, 46, 47],
        [32, 33, 34, 35,  0,  0,  0,  0],
        [36, 37, 38, 39,  0,  0,  0,  0],
        [40, 41, 42, 43,  0,  0,  0,  0],
        [44, 45, 46, 47,  0,  

In [14]:
sess.run(y3)

array([[[ 0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11],
        [12, 13, 14, 15, 12, 13, 14, 15],
        [ 0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11],
        [12, 13, 14, 15, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 16, 17, 18, 19],
        [20, 21, 22, 23, 20, 21, 22, 23],
        [24, 25, 26, 27, 24, 25, 26, 27],
        [28, 29, 30, 31, 28, 29, 30, 31],
        [16, 17, 18, 19, 16, 17, 18, 19],
        [20, 21, 22, 23, 20, 21, 22, 23],
        [24, 25, 26, 27, 24, 25, 26, 27],
        [28, 29, 30, 31, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 32, 33, 34, 35],
        [36, 37, 38, 39, 36, 37, 38, 39],
        [40, 41, 42, 43, 40, 41, 42, 43],
        [44, 45, 46, 47, 44, 45, 46, 47],
        [32, 33, 34, 35, 32, 33, 34, 35],
        [36, 37, 38, 39, 36, 37, 38, 39],
        [40, 41, 42, 43, 40, 41, 42, 43],
        [44, 45, 46, 47, 44, 4

==========================================

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
y1 = tf.cast(tf.Variable(np.ones([5, 10])), tf.int32)
y1_b = tf.cast(tf.Variable(np.ones([5, 2])), tf.int32)

y1_c = tf.concat([y1, y1_b], axis=1)

In [3]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [4]:
sess.run(y1_c)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)

In [6]:
y1_c.get_shape()

TensorShape([Dimension(5), Dimension(12)])

=====================================

In [1]:
import numpy as np

In [2]:
# 2-dimensional normal distribution
sampleNo = 1000

mu = np.array([0, 0])
sigma = np.array([[1, 0.5], [0.5, 1]])
R = np.linalg.cholesky(sigma)
s = np.dot(np.random.randn(sampleNo, 2), R) + mu

In [3]:
s

array([[-1.19470404, -0.49877799],
       [-1.44963235, -1.94071011],
       [ 0.32874865,  0.44000653],
       ..., 
       [ 1.16457073,  0.42219099],
       [-1.36533182, -1.67703245],
       [-1.61288714,  0.78441906]])

In [5]:
# 3-dimensional normal distribution
sampleNo = 1000

mu = np.zeros(3)
sigma = np.diag(np.ones(3))
for i in range(sigma.shape[0]):
    for j in range(sigma.shape[1]):
        if i!=j:
            sigma[i, j] = 0.5
            
print sigma
            
R = np.linalg.cholesky(sigma)
s = np.dot(np.random.randn(sampleNo, 3), R) + mu

[[ 1.   0.5  0.5]
 [ 0.5  1.   0.5]
 [ 0.5  0.5  1. ]]


In [6]:
s

array([[ 1.67892979,  1.00949795, -0.24306586],
       [ 0.95749263,  1.14301574, -0.00480249],
       [ 1.59797403,  0.82896914,  0.12742011],
       ..., 
       [ 2.6208977 ,  0.17903275,  1.36195078],
       [-2.05148868, -0.33023996, -0.91090021],
       [ 1.10476179,  0.0234182 ,  0.00430271]])

=========================

In [7]:
import numpy as np

In [9]:
y = np.ones([5, 10])
yb = np.ones([5, 2])

np.concatenate([y, yb], axis=1)
np.concatenate([y, yb], axis=1).shape

(5, 12)

In [10]:
np.array([0, 0]).astype(np.float32)*5

array([ 0.,  0.], dtype=float32)

In [13]:
np.tile(reps=np.array([0, 0]).astype(np.float32), A=[5]).shape

(0, 0)

In [29]:
yb = np.array([[0, 1]]*5)

In [30]:
yb

array([[0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1]])